### ISSUE TITLE
SQL errors when navigating to the 'tasks' or 'run charts' tabs

### ISSUE THREAD

**Issue by nl0** [iRessources/AgileDwarf#14]
I get sql errors while trying to open the 'tasks' or 'run charts' tabs.

I`m using postgres 8.4 and redmine 2.0.3.

Relevant log parts:

'tasks' tab:

```
Started GET "/adtasks/list?project_id=taxisoft" for 192.168.0.221 at 2012-08-07 00:16:30 +0600
Processing by AdtasksController#list as HTML
  Parameters: {"project_id"=>"taxisoft"}
   (0.6ms)  SELECT MAX("settings"."updated_on") AS max_id FROM "settings" 
  User Load (74.7ms)  SELECT "users".* FROM "users" WHERE "users"."type" IN ('User', 'AnonymousUser') AND "users"."id" = $1 AND (users.status = 1) LIMIT 1  [["id", 4]]
  Project Load (0.6ms)  SELECT "projects".* FROM "projects" WHERE "projects"."identifier" = 'taxisoft' LIMIT 1
  EnabledModule Load (0.4ms)  SELECT name FROM "enabled_modules" WHERE "enabled_modules"."project_id" = 1
  Setting Load (0.3ms)  SELECT "settings".* FROM "settings" WHERE "settings"."name" = 'issue_group_assignment' LIMIT 1
  SQL (1.6ms)  SELECT "members"."id" AS t0_r0, "members"."user_id" AS t0_r1, "members"."project_id" AS t0_r2, "members"."created_on" AS t0_r3, "members"."mail_notification" AS t0_r4, "users"."id" AS t1_r0, "users"."login" AS t1_r1, "users"."hashed_password" AS t1_r2, "users"."firstname" AS t1_r3, "users"."lastname" AS t1_r4, "users"."mail" AS t1_r5, "users"."admin" AS t1_r6, "users"."status" AS t1_r7, "users"."last_login_on" AS t1_r8, "users"."language" AS t1_r9, "users"."auth_source_id" AS t1_r10, "users"."created_on" AS t1_r11, "users"."updated_on" AS t1_r12, "users"."type" AS t1_r13, "users"."identity_url" AS t1_r14, "users"."mail_notification" AS t1_r15, "users"."salt" AS t1_r16, "roles"."id" AS t2_r0, "roles"."name" AS t2_r1, "roles"."position" AS t2_r2, "roles"."assignable" AS t2_r3, "roles"."builtin" AS t2_r4, "roles"."permissions" AS t2_r5, "roles"."issues_visibility" AS t2_r6 FROM "members" LEFT OUTER JOIN "users" ON "users"."id" = "members"."user_id" AND "users"."type" IN ('User', 'AnonymousUser') LEFT OUTER JOIN "member_roles" ON "member_roles"."member_id" = "members"."id" LEFT OUTER JOIN "roles" ON "roles"."id" = "member_roles"."role_id" WHERE "members"."project_id" = 1 AND (users.type='User' AND users.status=1)
  Principal Load (0.5ms)  SELECT "users".* FROM "users" WHERE "users"."id" = 4 LIMIT 1
  Sprints Load (0.7ms)  SELECT "versions".* FROM "versions" WHERE (status = 'open' and project_id = 1) ORDER BY ir_start_date ASC, ir_end_date ASC
  Setting Load (0.4ms)  SELECT "settings".* FROM "settings" WHERE "settings"."name" = 'plugin_AgileDwarf' LIMIT 1
  IssueStatus Load (0.5ms)  SELECT "issue_statuses".* FROM "issue_statuses" WHERE "issue_statuses"."id" IN (1, 2, 3)
  SprintsTasks Load (26.0ms)  SELECT issues.*, sum(hours) as spent FROM "issues" left join time_entries ON time_entries.issue_id = issues.id WHERE (issues.project_id = 1 and status_id = 1 and fixed_version_id = '1' and assigned_to_id = 4) GROUP BY issues.id ORDER BY case when issues.ir_position is null then 1 else 0 end ASC, case when issues.ir_position is NULL then issues.id else issues.ir_position end ASC
PG::Error: ERROR:  column "issues.tracker_id" must appear in the GROUP BY clause or be used in an aggregate function
СТРОКА 1:SELECT issues.*, sum(hours) as spent FROM "issues" left join...
                ^
: SELECT issues.*, sum(hours) as spent FROM "issues" left join time_entries ON time_entries.issue_id = issues.id WHERE (issues.project_id = 1 and status_id = 1 and fixed_version_id = '1' and assigned_to_id = 4) GROUP BY issues.id ORDER BY case when issues.ir_position is null then 1 else 0 end ASC, case when issues.ir_position is NULL then issues.id else issues.ir_position end ASC
Completed 500 Internal Server Error in 593ms

ActiveRecord::StatementInvalid (PG::Error: ERROR:  column "issues.tracker_id" must appear in the GROUP BY clause or be used in an aggregate function
СТРОКА 1:SELECT issues.*, sum(hours) as spent FROM "issues" left join...
                ^
: SELECT issues.*, sum(hours) as spent FROM "issues" left join time_entries ON time_entries.issue_id = issues.id WHERE (issues.project_id = 1 and status_id = 1 and fixed_version_id = '1' and assigned_to_id = 4) GROUP BY issues.id ORDER BY case when issues.ir_position is null then 1 else 0 end ASC, case when issues.ir_position is NULL then issues.id else issues.ir_position end ASC):
  activerecord (3.2.6) lib/active_record/connection_adapters/postgresql_adapter.rb:1151:in `async_exec'
  activerecord (3.2.6) lib/active_record/connection_adapters/postgresql_adapter.rb:1151:in `exec_no_cache'
  activerecord (3.2.6) lib/active_record/connection_adapters/postgresql_adapter.rb:664:in `block in exec_query'
  activerecord (3.2.6) lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
  activesupport (3.2.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activerecord (3.2.6) lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
  activerecord (3.2.6) lib/active_record/connection_adapters/postgresql_adapter.rb:663:in `exec_query'
  activerecord (3.2.6) lib/active_record/connection_adapters/postgresql_adapter.rb:1246:in `select'
  activerecord (3.2.6) lib/active_record/connection_adapters/abstract/database_statements.rb:18:in `select_all'
  activerecord (3.2.6) lib/active_record/connection_adapters/abstract/query_cache.rb:61:in `block in select_all'
  activerecord (3.2.6) lib/active_record/connection_adapters/abstract/query_cache.rb:75:in `cache_sql'
  activerecord (3.2.6) lib/active_record/connection_adapters/abstract/query_cache.rb:61:in `select_all'
  activerecord (3.2.6) lib/active_record/querying.rb:38:in `block in find_by_sql'
  activerecord (3.2.6) lib/active_record/explain.rb:40:in `logging_query_plan'
  activerecord (3.2.6) lib/active_record/querying.rb:37:in `find_by_sql'
  activerecord (3.2.6) lib/active_record/relation.rb:174:in `block in exec_queries'
  activerecord (3.2.6) lib/active_record/identity_map.rb:72:in `without'
  activerecord (3.2.6) lib/active_record/relation.rb:173:in `exec_queries'
  activerecord (3.2.6) lib/active_record/relation.rb:160:in `block in to_a'
  activerecord (3.2.6) lib/active_record/explain.rb:40:in `logging_query_plan'
  activerecord (3.2.6) lib/active_record/relation.rb:159:in `to_a'
  activerecord (3.2.6) lib/active_record/relation/finder_methods.rb:159:in `all'
  activerecord (3.2.6) lib/active_record/relation/finder_methods.rb:105:in `find'
  activerecord (3.2.6) lib/active_record/relation/finder_methods.rb:101:in `find'
  activerecord (3.2.6) lib/active_record/querying.rb:5:in `find'
  plugins/AgileDwarf/app/models/sprints_tasks.rb:24:in `get_tasks_by_status'
  plugins/AgileDwarf/app/controllers/adtasks_controller.rb:33:in `list'
  actionpack (3.2.6) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.6) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.6) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.6) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (3.2.6) lib/active_support/callbacks.rb:469:in `_run__922089545__process_action__603789579__callbacks'
  activesupport (3.2.6) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.6) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.6) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.6) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.6) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.2.6) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.6) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.6) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.6) lib/action_controller/metal/params_wrapper.rb:206:in `process_action'
  activerecord (3.2.6) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (3.2.6) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.6) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.6) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.6) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.6) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.6) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (3.2.6) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.6) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.6) lib/action_dispatch/routing/route_set.rb:600:in `call'
  rack-openid (1.3.1) lib/rack/openid.rb:98:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.1) lib/rack/etag.rb:23:in `call'
  rack (1.4.1) lib/rack/conditionalget.rb:25:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.1) lib/rack/session/abstract/id.rb:205:in `context'
  rack (1.4.1) lib/rack/session/abstract/id.rb:200:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/cookies.rb:338:in `call'
  activerecord (3.2.6) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:473:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.6) lib/active_support/callbacks.rb:405:in `_run__192934387__call__319732658__callbacks'
  activesupport (3.2.6) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.6) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.6) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.6) lib/rails/rack/logger.rb:26:in `call_app'
  railties (3.2.6) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.1) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.1) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.6) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.1) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/static.rb:62:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.6) lib/rails/engine.rb:479:in `call'
  railties (3.2.6) lib/rails/application.rb:220:in `call'
  railties (3.2.6) lib/rails/railtie/configurable.rb:30:in `method_missing'
```

'run charts' tab:

```
Started GET "/adburndown/show?project_id=taxisoft" for 192.168.0.221 at 2012-08-07 00:13:32 +0600
Processing by AdburndownController#show as HTML
  Parameters: {"project_id"=>"taxisoft"}
   (0.3ms)  SELECT MAX("settings"."updated_on") AS max_id FROM "settings" 
  User Load (0.3ms)  SELECT "users".* FROM "users" WHERE "users"."type" IN ('User', 'AnonymousUser') AND "users"."id" = $1 AND (users.status = 1) LIMIT 1  [["id", 4]]
  Project Load (0.3ms)  SELECT "projects".* FROM "projects" WHERE "projects"."identifier" = 'taxisoft' LIMIT 1
  EnabledModule Load (0.3ms)  SELECT name FROM "enabled_modules" WHERE "enabled_modules"."project_id" = 1
  SQL (1.0ms)  SELECT "members"."id" AS t0_r0, "members"."user_id" AS t0_r1, "members"."project_id" AS t0_r2, "members"."created_on" AS t0_r3, "members"."mail_notification" AS t0_r4, "users"."id" AS t1_r0, "users"."login" AS t1_r1, "users"."hashed_password" AS t1_r2, "users"."firstname" AS t1_r3, "users"."lastname" AS t1_r4, "users"."mail" AS t1_r5, "users"."admin" AS t1_r6, "users"."status" AS t1_r7, "users"."last_login_on" AS t1_r8, "users"."language" AS t1_r9, "users"."auth_source_id" AS t1_r10, "users"."created_on" AS t1_r11, "users"."updated_on" AS t1_r12, "users"."type" AS t1_r13, "users"."identity_url" AS t1_r14, "users"."mail_notification" AS t1_r15, "users"."salt" AS t1_r16, "roles"."id" AS t2_r0, "roles"."name" AS t2_r1, "roles"."position" AS t2_r2, "roles"."assignable" AS t2_r3, "roles"."builtin" AS t2_r4, "roles"."permissions" AS t2_r5, "roles"."issues_visibility" AS t2_r6 FROM "members" LEFT OUTER JOIN "users" ON "users"."id" = "members"."user_id" AND "users"."type" IN ('User', 'AnonymousUser') LEFT OUTER JOIN "member_roles" ON "member_roles"."member_id" = "members"."id" LEFT OUTER JOIN "roles" ON "roles"."id" = "member_roles"."role_id" WHERE "members"."project_id" = 1 AND (users.type='User' AND users.status=1)
  Principal Load (0.4ms)  SELECT "users".* FROM "users" WHERE "users"."id" = 4 LIMIT 1
  TimeEntry Load (0.5ms)  SELECT spent_on, sum(hours) as spent FROM "time_entries" INNER JOIN "issues" ON "issues"."id" = "time_entries"."issue_id" WHERE (time_entries.project_id = 1) GROUP BY spent_on
  SprintsTasks Load (0.3ms)  SELECT DATE(created_on) as created_on, id, done_ratio, estimated_hours FROM "issues" WHERE (project_id = 1)
   (0.4ms)  select * from (select old_value as value, journalized_id as issueId, prop_key, DATE(journals.created_on) created_on from `journals` inner join journal_details on (journals.id = journal_id) inner join issues on (issues.id = journalized_id) where journalized_type = 'Issue' and property = 'attr' and (prop_key = 'estimated_hours' or prop_key = 'done_ratio') and project_id = 1 order by journals.id desc) a group by `issueId`, created_on, prop_key order by created_on desc
PG::Error: ERROR:  syntax error at or near "`"
СТРОКА 1:...op_key, DATE(journals.created_on) created_on from `journals`...
                                                              ^
: select * from (select old_value as value, journalized_id as issueId, prop_key, DATE(journals.created_on) created_on from `journals` inner join journal_details on (journals.id = journal_id) inner join issues on (issues.id = journalized_id) where journalized_type = 'Issue' and property = 'attr' and (prop_key = 'estimated_hours' or prop_key = 'done_ratio') and project_id = 1 order by journals.id desc) a group by `issueId`, created_on, prop_key order by created_on desc
Completed 500 Internal Server Error in 16ms

ActiveRecord::StatementInvalid (PG::Error: ERROR:  syntax error at or near "`"
СТРОКА 1:...op_key, DATE(journals.created_on) created_on from `journals`...
                                                              ^
: select * from (select old_value as value, journalized_id as issueId, prop_key, DATE(journals.created_on) created_on from `journals` inner join journal_details on (journals.id = journal_id) inner join issues on (issues.id = journalized_id) where journalized_type = 'Issue' and property = 'attr' and (prop_key = 'estimated_hours' or prop_key = 'done_ratio') and project_id = 1 order by journals.id desc) a group by `issueId`, created_on, prop_key order by created_on desc):
  activerecord (3.2.6) lib/active_record/connection_adapters/postgresql_adapter.rb:1151:in `async_exec'
  activerecord (3.2.6) lib/active_record/connection_adapters/postgresql_adapter.rb:1151:in `exec_no_cache'
  activerecord (3.2.6) lib/active_record/connection_adapters/postgresql_adapter.rb:664:in `block in exec_query'
  activerecord (3.2.6) lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
  activesupport (3.2.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activerecord (3.2.6) lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
  activerecord (3.2.6) lib/active_record/connection_adapters/postgresql_adapter.rb:663:in `exec_query'
  activerecord (3.2.6) lib/active_record/connection_adapters/postgresql_adapter.rb:1246:in `select'
  activerecord (3.2.6) lib/active_record/connection_adapters/abstract/database_statements.rb:18:in `select_all'
  activerecord (3.2.6) lib/active_record/connection_adapters/abstract/query_cache.rb:61:in `block in select_all'
  activerecord (3.2.6) lib/active_record/connection_adapters/abstract/query_cache.rb:75:in `cache_sql'
  activerecord (3.2.6) lib/active_record/connection_adapters/abstract/query_cache.rb:61:in `select_all'
  plugins/AgileDwarf/app/controllers/adburndown_controller.rb:57:in `show'
  actionpack (3.2.6) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.6) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.6) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.6) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (3.2.6) lib/active_support/callbacks.rb:469:in `_run__607556119__process_action__338495397__callbacks'
  activesupport (3.2.6) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.6) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.6) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.6) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.6) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.2.6) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.6) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.6) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.6) lib/action_controller/metal/params_wrapper.rb:206:in `process_action'
  activerecord (3.2.6) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (3.2.6) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.6) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.6) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.6) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.6) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.6) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (3.2.6) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.6) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.6) lib/action_dispatch/routing/route_set.rb:600:in `call'
  rack-openid (1.3.1) lib/rack/openid.rb:98:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.1) lib/rack/etag.rb:23:in `call'
  rack (1.4.1) lib/rack/conditionalget.rb:25:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.1) lib/rack/session/abstract/id.rb:205:in `context'
  rack (1.4.1) lib/rack/session/abstract/id.rb:200:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/cookies.rb:338:in `call'
  activerecord (3.2.6) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:473:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.6) lib/active_support/callbacks.rb:405:in `_run__94665435__call__505057416__callbacks'
  activesupport (3.2.6) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.6) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.6) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.6) lib/rails/rack/logger.rb:26:in `call_app'
  railties (3.2.6) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.1) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.1) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.6) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.1) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/static.rb:62:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.6) lib/rails/engine.rb:479:in `call'
  railties (3.2.6) lib/rails/application.rb:220:in `call'
  railties (3.2.6) lib/rails/railtie/configurable.rb:30:in `method_missing'
```

**Comment by markablov** [comment]
PostgreSQL version now in work.
