### ISSUE TITLE
Error on issue view after installing AgileDwarf in Redmine 2.4.2

### ISSUE THREAD

**Issue by hikaru-shindo** [iRessources/AgileDwarf#79]
I can't access the issue overview anymore after installing AgileDwarf to Redmine 2.4.2:

<pre>ActiveRecord::SubclassNotFound (The single-table inheritance mechanism failed to locate the subclass: 'ScrumblerIssueCustomField'. This error is raised because the column 'type' is reserved for storing the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite CustomField.inheritance_column to use another column for that information.):
  app/models/query.rb:812:in `add_associations_custom_fields_filters'
  app/models/issue_query.rb:237:in `initialize_available_filters'
  app/models/query.rb:329:in `available_filters'
  app/models/query.rb:220:in `build_from_params'
  app/models/issue_query.rb:119:in `build_from_params'
  app/helpers/queries_helper.rb:197:in `retrieve_query'
  app/controllers/issues_controller.rb:56:in `index'</pre>

**Comment by hikaru-shindo** [comment]
Was a problem with old database entries not removed by migrate.
