### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by chesterman** [iRessources/AgileDwarf#8]
Hi.
I'm running redmine 1.4.4. I decompressed the zip in the vendor/plugin folder, renamed to AgileDwarf and when i try to activate the module in one of my projects, i got a error 500. Here is the redmine log:

Processing ProjectsController#modules (for 192.168.1.104 at 2012-07-31 16:05:28) [POST]
  Parameters: {"authenticity_token"=>"93KU22Ws2brstVJ2QRuc+L46kLO4YAdt/eWCEYgp6r4=", "enabled_module_names"=>["issue_tracking", "time_tracking", "wiki", "gantt", "scrum"], "commit"=>"Salvar", "id"=>"hardware", "controller"=>"projects", "action"=>"modules"}

ActiveRecord::StatementInvalid (PG::Error: ERROR:  column "ir_position" does not exist
LINE 1: select max(ir_position) from issues where project_id =  31
                   ^
: select max(ir_position) from issues where project_id =  31):
  app/models/project.rb:577:in `enabled_module_names='
  app/controllers/projects_controller.rb:208:in`modules'
  /usr/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
  /usr/lib/ruby/1.8/webrick/httpserver.rb:65:in`run'
  /usr/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
  /usr/lib/ruby/1.8/webrick/server.rb:162:in`start'
  /usr/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
  /usr/lib/ruby/1.8/webrick/server.rb:95:in`start'
  /usr/lib/ruby/1.8/webrick/server.rb:92:in `each'
  /usr/lib/ruby/1.8/webrick/server.rb:92:in`start'
  /usr/lib/ruby/1.8/webrick/server.rb:23:in `start'
  /usr/lib/ruby/1.8/webrick/server.rb:82:in`start'

Rendering /opt/redmine-1.4.4/public/500.html (500 Internal Server Error)

Any ideas? Tks in advance.

**Comment by chesterman** [comment]
Also, i could not run the rake command:

root@cammy:/opt/redmine# RAILS_ENV=production rake redmine:plugins:migrate
Please install RDoc 2.4.2+ to generate documentation.
rake aborted!
Don't know how to build task 'redmine:plugins:migrate'

(See full trace by running task with --trace)

**Comment by chesterman** [comment]
ok, runned the following comand fixed the problem:

RAILS_ENV=production rake db:migrate:plugin NAME=AgileDwarf
