### ISSUE TITLE
Redmine 3.0 suport

### ISSUE THREAD

**Issue by dawidcieszynski** [iRessources/AgileDwarf#83]
Current version doesn't work on Redmine 3.0.1.stable.14155.
Installation require modification of plugins/AgileDwarf/config/routes.rb and even after succesfull install, all pages give "Internal error".

**Comment by colinexl** [comment]
same issue here.

**Comment by jjrosalesuci** [comment]
same issue here.

**Comment by knvmmohan** [comment]
yes same issue

```
ctiveRecord::RecordNotFound (Couldn't find all SprintsTasks with 'id': (all, {:order=>"case when issues.ir_position is null then 1 else 0 end ASC, case when issues.ir_position is NULL then issues.id else issues.ir_position end ASC", :conditions=>["project_id = ? and is_closed = ? and fixed_version_id is null", 20, false], :joins=>:status, :include=>:assigned_to}) (found 0 results, but was looking for 2)):
  activerecord (4.2.1) lib/active_record/relation/finder_methods.rb:336:in `raise_record_not_found_exception!'
  activerecord (4.2.1) lib/active_record/relation/finder_methods.rb:479:in `find_some'
  activerecord (4.2.1) lib/active_record/relation/finder_methods.rb:438:in `find_with_ids'
  activerecord (4.2.1) lib/active_record/relation/finder_methods.rb:71:in `find'
  activerecord (4.2.1) lib/active_record/querying.rb:3:in `find'
  activerecord (4.2.1) lib/active_record/core.rb:128:in `find'
  plugins/AgileDwarf/app/models/sprints_tasks.rb:40:in `get_tasks_by_sprint'
  plugins/AgileDwarf/app/models/sprints_tasks.rb:45:in `get_backlog'
  plugins/AgileDwarf/app/controllers/adsprints_controller.rb:7:in `list'
  actionpack (4.2.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.1) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.1) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.1) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.1) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.1) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `call'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
  rack-raw-upload (1.1.1) lib/rack/raw_upload.rb:18:in `call'
  rack-openid (1.4.2) lib/rack/openid.rb:98:in `call'
  request_store (1.0.5) lib/request_store/middleware.rb:9:in `call'
  rack (1.6.0) lib/rack/etag.rb:24:in `call'
  rack (1.6.0) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.0) lib/rack/head.rb:13:in `call'
  actionpack-xml_parser (1.0.2) lib/action_dispatch/xml_params_parser.rb:16:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.0) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.0) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.1) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.0) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.0) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.1) lib/rails/application.rb:164:in `call'
  rack (1.6.0) lib/rack/lock.rb:17:in `call'
  rack (1.6.0) lib/rack/content_length.rb:15:in `call'
  rack (1.6.0) lib/rack/handler/webrick.rb:89:in `service'
  /usr/local/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
  /usr/local/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
  /usr/local/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

**Comment by tolstenko** [comment]
This an awesome plugin to die this way... :/

**Comment by Slind14** [comment]
:+1:

**Comment by skynet2982** [comment]
+1

**Comment by luizferreira** [comment]
+1!

**Comment by jbh** [comment]
+1

**Comment by cognitus** [comment]
any news?

**Comment by doctorkb** [comment]
I got it to work better than suggested, it seems.

Had to add mysql (not mysql2) driver to my gemfile, and amend the routes.rb to match new syntax.

Once that's done, I don't get an "error" per se, but just:
"Page not found

The page you were trying to access doesn't exist or has been removed."

when I try to go to any of the AgileDwarf pages (e.g. http://hostname/adsprints/list?project_id=test)

**Comment by greenius** [comment]
I've updated the database queries to work with rails 4.2.4, redmine 3.1.1-stable... https://github.com/greenius/agile_dwarf
I'm not a rails expert so someone else could probably do a better job, but at least it seems to work again.

**Comment by doctorkb** [comment]
Thanks greenius!

I've only found one issue -- in trying to update fields (e.g. completed %, estimated hours, assignments, etc.) on the Sprints or Tasks tabs, I get this logged:

```
ESC[1mESC[36mSprintsTasks Load (0.5ms)ESC[0m  ESC[1mSELECT `issues`.* FROM `issues` WHERE `issues`.`id` IN (1696, NULL)ESC[0m
Completed 404 Not Found in 15ms (ActiveRecord: 2.3ms)

ActiveRecord::RecordNotFound (Couldn't find all SprintsTasks with 'id': (1696, {:include=>:assigned_to}) (found 1 results, but was looking for 2)):
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

Any thoughts?

**Comment by doctorkb** [comment]
Well, found a fix.  Not sure if I broke something else yet, but _shrug_.
adtaskinl_controller.rb:71
change
task = SprintsTasks.find(params[:id], :include => :assigned_to)
to
task = SprintsTasks.find(params[:id])

**Comment by ArkadiuszZolnik** [comment]
Here you have fork that works:
https://github.com/alfajango/AgileDwarf
